Updates to support isort v5 (#395)
* Removed `not_skip` and `recursive` from `tox.ini`

Fixes "TypeError: __init__() got an unexpected keyword argument 'not_skip'" introduced by the deprecation of the not_skip in isort v5. Recursive traversal is now the default behavior in isort v5.

See: https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/

* Add `python_requires=">=3.6"` to setup.py